apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: cluster1
  git:
    syncRepo: https://github.com/manikanth-k/anthos.git
    syncBranch: master
    secretType: none
    policyDir: "."
    syncWait: 2
  enableAggregateNamespaceQuotas: true
  enableHierarchicalResourceQuotas: true
